name: IaC Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/'

permissions:
    contents: read
    id-token: write

jobs:
    apply:
        name: Terraform Deploy
        runs-on: ubuntu-latest
        environment: prod

        defaults:
            run:
                working-directory: ./infrastructure/

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.13.0

            - name: Terraform Init
              run: |
                terraform init -input=false \
                  -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
                  -backend-config="key=${{ secrets.TF_STATE_KEY || 'dev/terraform.tfstate' }}" \
                  -backend-config="region=us-east-1" \
                  -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
                  -backend-config="encrypt=true"

            - name: Terraform Plan
              id: plan
              run: terraform plan -input=false -out=tfplan

            - name: Terraform Apply
              run: terraform apply -input=false -auto-approve tfplan